{
    "identifiers": [
        "Autodesk",
        "Revit",
        "DB",
        "Autodesk",
        "Revit",
        "DB",
        "Structure",
        "BH",
        "Engine",
        "Adapters",
        "Revit",
        "BH",
        "Revit",
        "Engine",
        "Core",
        "BH",
        "Engine",
        "Geometry",
        "BH",
        "oM",
        "Adapters",
        "Revit",
        "Settings",
        "BH",
        "oM",
        "Base",
        "BH",
        "oM",
        "Geometry",
        "ShapeProfiles",
        "BH",
        "oM",
        "MEP",
        "SectionProperties",
        "BH",
        "oM",
        "MEP",
        "Elements",
        "BH",
        "oM",
        "Reflection",
        "Attributes",
        "BH",
        "oM",
        "Structure",
        "Elements",
        "BH",
        "oM",
        "Structure",
        "MaterialFragments",
        "BH",
        "oM",
        "Structure",
        "SectionProperties",
        "Collections",
        "Generic",
        "ComponentModel",
        "BH",
        "oM",
        "Geometry",
        "Linq",
        "BH",
        "oM",
        "MEP",
        "MaterialFragments",
        "Autodesk",
        "Revit",
        "DB",
        "Mechanical",
        "BH",
        "Revit",
        "Engine",
        "Core",
        "Description",
        "Input",
        "Input",
        "Input",
        "Output",
        "BH",
        "oM",
        "MEP",
        "SectionProperties",
        "SectionProfile",
        "Autodesk",
        "Revit",
        "DB",
        "Mechanical",
        "Duct",
        "revitDuct",
        "RevitSettings",
        "settings",
        "IBHoMObject",
        "refObjects",
        "settings",
        "settings",
        "DefaultIfNull",
        "revitDuct",
        "DuctType",
        "ProfileFromRevit",
        "revitDuct",
        "settings",
        "refObjects",
        "revitDuct",
        "LookupParameterDouble",
        "revitDuct",
        "LookupParameterDouble",
        "Autodesk",
        "Revit",
        "DB",
        "ConnectorProfileType",
        "BH",
        "Revit",
        "Engine",
        "Core",
        "Query",
        "DuctShape",
        "revitDuct",
        "settings",
        "ductShape",
        "Autodesk",
        "Revit",
        "DB",
        "ConnectorProfileType",
        "Round",
        "BH",
        "Engine",
        "MEP",
        "Create",
        "SectionProfile",
        "TubeProfile",
        "profile",
        "liningThickness",
        "insulationThickness",
        "Autodesk",
        "Revit",
        "DB",
        "ConnectorProfileType",
        "Rectangular",
        "BH",
        "Engine",
        "MEP",
        "Create",
        "SectionProfile",
        "BoxProfile",
        "profile",
        "liningThickness",
        "insulationThickness",
        "Autodesk",
        "Revit",
        "DB",
        "ConnectorProfileType",
        "Oval",
        "BH",
        "Engine",
        "Reflection",
        "Compute",
        "RecordWarning"
    ],
    "literals": [
        "\"Section profile of round and rectangular ducts.\"",
        "\"Autodesk.Revit.DB.Mechanical.DuctType\"",
        "\"Revit duct type.\"",
        "\"BH.oM.Adapters.Revit.Settings.RevitSettings\"",
        "\"Revit settings.\"",
        "\"Dictionary<string, List<IBHoMObject>>\"",
        "\"Referenced objects.\"",
        "\"BH.oM.MEP.SectionProperties.SectionProfile\"",
        "\"BHoM section property.\"",
        "\"Lining Thickness\"",
        "\"Insulation Thickness\"",
        "\"There is currently no section profile for an oval duct in BHoM_Engine.\""
    ],
    "variables": [
        "IProfile",
        "profile",
        "liningThickness",
        "insulationThickness",
        "ductShape"
    ],
    "comments": [
        "Lining thickness",
        "Insulation thickness",
        "Get the duct shape, which is either circular, rectangular, oval or null",
        "Is the duct circular, rectangular or oval?",
        "Create an oval profile",
        "There is currently no section profile for an oval duct in BHoM_Engine. This part will be implemented once the relevant section profile becomes available."
    ],
    "docstrings": [
        "* This file is part of the Buildings and Habitats object Model (BHoM)\n * Copyright (c) 2015 - 2020, the respective contributors. All rights reserved.\n *\n * Each contributor holds copyright over their respective contributions.\n * The project versioning (Git) records all such contribution source information.\n *                                           \n *                                                                              \n * The BHoM is free software: you can redistribute it and/or modify         \n * it under the terms of the GNU Lesser General Public License as published by  \n * the Free Software Foundation, either version 3.0 of the License, or          \n * (at your option) any later version.                                          \n *                                                                              \n * The BHoM is distributed in the hope that it will be useful,              \n * but WITHOUT ANY WARRANTY; without even the implied warranty of               \n * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the                 \n * GNU Lesser General Public License for more details.                          \n *                                                                            \n * You should have received a copy of the GNU Lesser General Public License     \n * along with this code. If not, see <https://www.gnu.org/licenses/lgpl-3.0.html>.",
        "************************************************",
        "**               Public Methods              ***",
        "************************************************",
        "************************************************"
    ],
    "functions": [
        "DuctSectionProfile"
    ],
    "classes": [
        "Query"
    ]
}