{
    "identifiers": [
        "os",
        "rpw",
        "revit",
        "Autodesk",
        "Revit",
        "UI",
        "Selection",
        "Autodesk",
        "Revit",
        "DB",
        "pyrevit",
        "forms",
        "pyrevit",
        "output",
        "csv",
        "__revit__",
        "ActiveUIDocument",
        "Document",
        "forms",
        "pick_file",
        "title",
        "forms",
        "ask_for_string",
        "prompt",
        "title",
        "forms",
        "ask_for_string",
        "prompt",
        "title",
        "lenght_real_centimeters",
        "lenght_pixels",
        "open",
        "csv_file_path",
        "csvfile",
        "csv",
        "DictReader",
        "csvfile",
        "delimiter",
        "quotechar",
        "row",
        "data",
        "data_file",
        "append",
        "row",
        "data_file",
        "FilteredElementCollector",
        "doc",
        "OfCategory",
        "BuildInCategory",
        "OST_Levels",
        "WhereElementIsNotElementType",
        "ToElements",
        "FilteredElementCollector",
        "doc",
        "OfCategory",
        "BuildInCategory",
        "OST_Walls",
        "WhereElementIsNotElementType",
        "ToElements",
        "data_file",
        "a",
        "b"
    ],
    "literals": [
        "\"Pick file with exported csv\"",
        "'Write what is the lenght of measure object in pixels'",
        "'Set value'",
        "'Pixels lenght'",
        "'Write what is the real lenght of measure object in centimeters'",
        "'Set value'",
        "'Real lenght'",
        "','",
        "'|'",
        "\"xmax\"",
        "\"xmin\"",
        "\"ymax\"",
        "\"ymin\"",
        "\"xmax\""
    ],
    "variables": [
        "doc",
        "csv_file_path",
        "lenght_pixels",
        "lenght_real_centimeters",
        "scale",
        "data_file",
        "data",
        "levels",
        "walls",
        "curves_list",
        "a",
        "b",
        "x1"
    ],
    "comments": [
        "def / class",
        "Pick file with csv",
        "Ask for 3D view name to export",
        "Calculate scale",
        "Create walls",
        "Import csv",
        "Create walls",
        "Collect levels and walls types",
        "Collect walls curves",
        "open_options = OpenOptions()",
        "open_options.DetachFromCentralOption = DetachFromCentralOption.DetachAndPreserveWorksets",
        "name=0",
        "for revit_model in models_paths:",
        "revit_model_path = ModelPathUtils.ConvertUserVisiblePathToModelPath(revit_model)",
        "doc_nwc = __revit__.Application.OpenDocumentFile(revit_model_path, open_options)",
        "# NWCExportScope = System.Enum.GetValues(NavisworksExportScope)[1]",
        "# ChooseCoordinates = System.Enum.GetValues(NavisworksCoordinates)[0]",
        "Linksbool = False",
        "views = FilteredElementCollector(doc_nwc).OfCategory(BuiltInCategory.OST_Views).WhereElementIsNotElementType().ToElements()",
        "name=revit_model",
        "for view in views:",
        "if view.IsTemplate != True and str(view.Name)==view_name_3D:",
        "view_export = view",
        "ExportNWC(str(name), view_export, models_folder, doc_nwc)",
        "print(view_export)",
        "print(name)",
        "doc_nwc.Close(False)",
        "print(view_name_3D)"
    ],
    "docstrings": [],
    "functions": [],
    "classes": []
}