{
    "identifiers": [
        "Collections",
        "Generic",
        "Linq",
        "Text",
        "Threading",
        "Tasks",
        "Autodesk",
        "Revit",
        "DB",
        "Autodesk",
        "Revit",
        "UI",
        "DougKlassen",
        "Revit",
        "Perfect",
        "Commands",
        "SplitWallByLevelCommand",
        "Autodesk",
        "Revit",
        "Attributes",
        "Transaction",
        "Autodesk",
        "Revit",
        "Attributes",
        "TransactionMode",
        "Manual",
        "IExternalCommand",
        "ExternalCommandData",
        "commandData",
        "message",
        "ElementSet",
        "elements",
        "commandData",
        "Application",
        "ActiveUIDocument",
        "uiDoc",
        "Document",
        "uiDoc",
        "Selection",
        "GetElementIds",
        "selection",
        "Count",
        "dbDoc",
        "GetElement",
        "selection",
        "First",
        "Wall",
        "TaskDialog",
        "Show",
        "Result",
        "Failed",
        "dbDoc",
        "GetElement",
        "selection",
        "First",
        "Wall",
        "dbDoc",
        "GetElement",
        "wall",
        "get_Parameter",
        "BuiltInParameter",
        "WALL_BASE_CONSTRAINT",
        "AsElementId",
        "Level",
        "wall",
        "get_Parameter",
        "BuiltInParameter",
        "WALL_BASE_OFFSET",
        "AsDouble",
        "bottomElevation",
        "bottomLevel",
        "Elevation",
        "bottomOffset",
        "wall",
        "get_Parameter",
        "BuiltInParameter",
        "WALL_HEIGHT_TYPE",
        "AsElementId",
        "wallTopLevelID",
        "topLevel",
        "dbDoc",
        "GetElement",
        "wallTopLevelID",
        "Level",
        "wall",
        "get_Parameter",
        "BuiltInParameter",
        "WALL_TOP_OFFSET",
        "AsDouble",
        "topElevation",
        "topLevel",
        "Elevation",
        "topOffset",
        "wall",
        "get_Parameter",
        "BuiltInParameter",
        "WALL_USER_HEIGHT_PARAM",
        "AsDouble",
        "topElevation",
        "bottomElevation",
        "unconnectedHeight",
        "FilteredElementCollector",
        "dbDoc",
        "OfCategory",
        "BuiltInCategory",
        "OST_Levels",
        "Select",
        "dbDoc",
        "GetElement",
        "e",
        "Id",
        "Level",
        "OrderBy",
        "l",
        "Elevation",
        "Level",
        "Level",
        "Transaction",
        "dbDoc",
        "t",
        "Start",
        "t",
        "Commit",
        "Result",
        "Succeeded"
    ],
    "literals": [
        "\"Select Wall\"",
        "\"Select a single wall to be split\""
    ],
    "variables": [
        "uiDoc",
        "dbDoc",
        "selection",
        "Wall",
        "wall",
        "bottomElevation",
        "topElevation",
        "Level",
        "bottomLevel",
        "bottomOffset",
        "Level",
        "topLevel",
        "wallTopLevelID",
        "topOffset",
        "unconnectedHeight",
        "levels",
        "levelsBetween",
        "Transaction",
        "t"
    ],
    "comments": [
        "cancel the command if the selection isn't of a single wall",
        "get the elevation at the bottom of the wall",
        "get the elevation at the top of the wall",
        "get the top level constraint of the wall. It will be null if the wall is unconnected",
        "if the wall is constrained to a top level",
        "if the wall is unconnected, the topElevation is the bottomElevation + the unconnected height",
        "get all levels in the document, sorted by elevation",
        "TODO: account for situation where top and bottom constraints skip levels",
        "TODO: let user select which levels will be used for splitting"
    ],
    "docstrings": [],
    "functions": [
        "Result",
        "Execute"
    ],
    "classes": [
        "SplitWallByLevelCommand"
    ]
}